language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - dist: xenial
      services: mongodb
      r_check_args: '--run-donttest'
    - os: osx
      brew_packages: openssl
      before_install:
        - brew unlink python #Python still broken in 2to3
        - brew install mongodb
        - brew services start mongodb
      r_check_args: '--run-donttest'
      warnings_are_errors: false #-Wno-deprecated-declarations
    - os: osx
      brew_packages: openssl@1.1
      before_install: brew uninstall --ignore-dependencies openssl
      env: PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
      warnings_are_errors: false  #-Wno-deprecated-declarations
    - os: osx
      brew_packages: libressl
      before_install: brew uninstall --ignore-dependencies openssl openssl@1.1
      env: PKG_CONFIG_PATH="/usr/local/opt/libressl/lib/pkgconfig"
      warnings_are_errors: false  #-Wno-deprecated-declarations
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      warnings_are_errors: false  #-Wno-deprecated-declarations
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      warnings_are_errors: false  #-Wno-deprecated-declarations
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf
      env: MONGOLITE_USE_OPENSSL=1

addons:
  apt:
    packages:
    - libssl-dev
    - libsasl2-dev
    - libicu-dev
    - valgrind
