language: r
cache: packages
latex: false
fortran: false

# needed for covr
services: mongodb

matrix:
  include:
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r_check_args: '--use-valgrind'
      r: devel
    - os: osx
      osx_image: xcode9.2
      brew_packages: openssl@1.1
    - os: osx
      osx_image: xcode9.2
      brew_packages: openssl
    - os: osx
      osx_image: xcode9.2
      brew_packages: libressl
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      latex: false

addons:
  apt:
    packages:
    - libssl-dev
    - libsasl2-dev
    - libicu-dev
    - valgrind

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
